export const movieQuotes = [
    "You're gonna need a bigger boat.",
    "Frankly, my dear, I don't give a damn.",
    "Mama always said life was like a box of chocolates.",
    "Toto, I've a feeling we're not in Kansas anymore.",
    "Here's looking at you, kid.",
    "Hasta la vista, baby.",
    "I feel the need—the need for speed!",
    "Chewie, we're home.",
    "You've got to ask yourself one question: 'Do I feel lucky? Well, do ya, punk?'",
    "You had me at 'hello.'",
    "Go ahead, make my day.",
    "May the Force be with you.",
    "You talkin' to me?",
    "I love the smell of napalm in the morning.",
    "E.T. phone home.",
    "Made it, Ma! Top of the world!",
    "I'm as mad as hell... and I'm not gonna take this anymore!",
    "Bond. James Bond.",
    "There's no place like home.",
    "Show me the money!",
    "You can't handle the truth!",
    "Round up the usual suspects.",
    "I'll have what she's having.",
    "I'll be back.",
    "Nobody puts Baby in a corner.",
    "That'll do, pig. That'll do.",
    "You're killin' me, Smalls!",
    "Talk to me, Goose.",
    "I'm king of the world!",
    "Carpe diem. Seize the day, boys.",
    "Elementary, my dear Watson.",
    "Badges? We ain't got no badges!",
    "They call me Mister Tibbs!",
    "I see dead people.",
    "Stella! Hey, Stella!",
    "Say 'hello' to my little friend!",
    "Greed, for lack of a better word, is good.",
    "It's alive! It's alive!",
    "Houston, we have a problem.",
    "Heeere's Johnny!",
    "Open the pod bay doors, please, HAL.",
    "Surely you can't be serious? I am serious... and don't call me Shirley.",
    "Yo, Adrian!",
    "Toga! Toga!",
    "Listen to them. Children of the night...",
    "My precious.",
    "Look at me, I'm the captain now.",
    "If you build it, he will come.",
    "We rob banks.",
    "We'll always have Paris.",
    "I'm walking here! I'm walking here!",
    "Gentlemen, you can't fight in here! This is the War Room!",
    "Mrs. Robinson, you're trying to seduce me.",
    "Get your stinking paws off me, you damned dirty ape!",
    "Oh, no, it wasn't the airplanes. 'Twas Beauty killed the Beast.",
    "Why so serious?",
    "This is Sparta!",
    "Avengers assemble!",
    "Good morning, Vietnam!",
    "You know how to whistle, don't you?",
    "We are not alone.",
    "In space, no one can hear you scream.",
    "Who you gonna call?",
    "Be afraid. Be very afraid.",
    "Love means never having to say you're sorry.",
    "It knows what scares you.",
    "Just when you thought it was safe to go back in the water...",
    "There's no crying in baseball!",
    "What's in the box?",
    "To infinity and beyond!",
    "I am your father.",
    "You shall not pass!",
    "This is the way.",
    "Not today, Satan!",
    "Wakanda forever!",
    "We're not in Kansas anymore.",
    "The first rule of Fight Club is: you do not talk about Fight Club.",
    "I'll never let go, Jack. I promise.",
    "I'm vengeance.",
    "I am Iron Man.",
    "I'm Batman.",
    "You either die a hero or live long enough to see yourself become the villain.",
    "Are you not entertained?",
    "That escalated quickly.",
    "They may take our lives, but they'll never take our freedom!",
    "To boldly go where no man has gone before.",
    "I'm having an old friend for dinner.",
    "No capes!",
    "You make me want to be a better man.",
    "I'm the dude, so that's what you call me.",
    "It's not who I am underneath, but what I do that defines me.",
    "I ate his liver with some fava beans and a nice Chianti.",
    "I volunteer as tribute!",
    "Leave the gun. Take the cannoli.",
    "Forget it, Jake, it's Chinatown.",
    "Soylent Green is people!",
    "Snap out of it!",
    "I'm the king of the world!",
    "A boy's best friend is his mother.",
    "You're tearing me apart, Lisa!",
    "I wish I knew how to quit you.",
    "With great power comes great responsibility.",
    "I'm too old for this shit.",
    "I'm not bad. I'm just drawn that way.",
    "They're here!",
    "Here's looking at you, kid.",
    "Wax on, wax off.",
    "It's just a flesh wound.",
    "I'm your Huckleberry.",
    "Well, nobody's perfect.",
    "I feel like I'm taking crazy pills!",
    "You had me at hello.",
    "I'm just a girl, standing in front of a boy, asking him to love her.",
    "Keep the change, ya filthy animal.",
    "So you're telling me there's a chance.",
    "60% of the time, it works every time.",
    "You're a wizard, Harry.",
    "I am Groot.",
    "As if!",
    "You're a mean one, Mr. Grinch.",
    "Mischief managed.",
    "I'll get you, my pretty, and your little dog, too!",
    "These go to eleven.",
    "I'm just one stomach flu away from my goal weight.",
    "They call it a Royale with cheese.",
    "Magic Mirror on the wall, who is the fairest one of all?",
    "I see your Schwartz is as big as mine.",
    "I love you 3000.",
    "Help me, Obi-Wan Kenobi. You're my only hope",
    "It's a trap!",
    "The Dude abides.",
    "Just keep swimming.",
    "The greatest trick the Devil ever pulled was convincing the world he didn't exist.",
    "Roads? Where we're going, we don't need roads.",
    "Yippee-ki-yay, motherf***er!",
    "Hello, my name is Inigo Montoya. You killed my father. Prepare to die.",
    "Looks like sombody's got a case of the Mondays.",
    "You take the red pill, you stay in Wonderland, and I show you how deep the rabbit hole goes.",
    "I live my life a quarter mile at a time.",
    "Gretchen, stop trying to make fetch happen. It's not going to happen.",
    "I am in a glass case of emotion!",
    "I have had it with these motherf***ing snakes on this motherf***ing plane!",
    "What is the most you ever lost on a coin toss?",
    "Now, you're in the sunken place.",


];
