export const movieQuotes = [
    "You're gonna need a bigger boat.",
    "Frankly, my dear, I don't give a damn.",
    "I'm gonna make him an offer he can't refuse.",
    "Mama always said life was like a box of chocolates.",
    "Toto, I've a feeling we're not in Kansas anymore.",
    "Here's looking at you, kid.",
    "Hasta la vista, baby.",
    "I feel the need—the need for speed!",
    "Chewie, we're home.",
    "You don't understand! I coulda had class...",
    "Not my tempo.",
    "You've got to ask yourself one question: 'Do I feel lucky? Well, do ya, punk?'",
    "You had me at 'hello.'",
    "Go ahead, make my day.",
    "May the Force be with you.",
    "Fasten your seatbelts. It's going to be a bumpy night.",
    "You talkin' to me?",
    "What we've got here is failure to communicate.",
    "I love the smell of napalm in the morning.",
    "E.T. phone home.",
    "Rosebud.",
    "Made it, Ma! Top of the world!",
    "I'm as mad as hell... and I'm not gonna take this anymore!",
    "A census taker once tried to test me...",
    "Bond. James Bond.",
    "There's no place like home.",
    "Show me the money!",
    "You can't handle the truth!",
    "After all, tomorrow is another day!",
    "Round up the usual suspects.",
    "I'll have what she's having.",
    "I'll be back.",
    "Life is not the amount of breaths...",
    "Nobody puts Baby in a corner.",
    "That'll do, pig. That'll do.",
    "You're killin' me, Smalls!",
    "Talk to me, Goose.",
    "I'm king of the world!",
    "Carpe diem. Seize the day, boys.",
    "Elementary, my dear Watson.",
    "Badges? We ain't got no badges!",
    "They call me Mister Tibbs!",
    "I see dead people.",
    "Stella! Hey, Stella!",
    "Say 'hello' to my little friend!",
    "Greed, for lack of a better word, is good.",
    "Keep your friends close, but your enemies closer.",
    "I want to be alone.",
    "It's alive! It's alive!",
    "Houston, we have a problem.",
    "One morning I shot an elephant in my pajamas...",
    "La-dee-da, la-dee-da.",
    "Heeere's Johnny!",
    "Open the pod bay doors, please, HAL.",
    "Surely you can't be serious? I am serious... and don't call me Shirley.",
    "Yo, Adrian!",
    "Hello, gorgeous.",
    "Toga! Toga!",
    "Listen to them. Children of the night...",
    "My precious.",
    "Attica! Attica!",
    "Life is a banquet, and most poor suckers are starving to death!",
    "Oh what a day... what a lovely day!",
    "Look at me, I'm the captain now.",
    "Today, I consider myself the luckiest man on the face of the earth.",
    "If you build it, he will come.",
    "We rob banks.",
    "Plastics.",
    "We'll always have Paris.",
    "Why don't you come up sometime and see me?",
    "I'm walking here! I'm walking here!",
    "Gentlemen, you can't fight in here! This is the War Room!",
    "Mrs. Robinson, you're trying to seduce me.",
    "Get your stinking paws off me, you damned dirty ape!",
    "Oh, no, it wasn't the airplanes. 'Twas Beauty killed the Beast.",
    "Why so serious?",
    "This is Sparta!",
    "Avengers assemble!",
    "Good morning, Vietnam!",
    "You know how to whistle, don't you?",
    "We are not alone.",
    "You'll believe a man can fly.",
    "In space, no one can hear you scream.",
    "Who you gonna call?",
    "Be afraid. Be very afraid.",
    "Garbo talks!",
    "Love means never having to say you're sorry.",
    "It knows what scares you.",
    "Some houses are born bad.",
    "Just when you thought it was safe to go back in the water...",
    "You must become Caligari!",
    "Garbo laughs!",
    "There's no crying in baseball!",
    "What's in the box?",
    "I drink your milkshake!",
    "To infinity and beyond!",
    "I am your father.",
    "You shall not pass!",
    "This is the way.",
    "Not today, Satan!",
    "Wakanda forever!",
    "We're not in Kansas anymore.",
    "The first rule of Fight Club is: you do not talk about Fight Club.",
    "I'll never let go, Jack. I promise.",
    "I see you.",
    "I'm vengeance.",
    "I am Iron Man.",
    "I'm Batman.",
    "You're breathtaking!",
    "You either die a hero or live long enough to see yourself become the villain.",
    "Are you not entertained?",
    "That escalated quickly.",
    "I am serious. And don't call me Shirley.",
    "Freedom!",
    "To boldly go where no man has gone before.",
    "I'm having an old friend for dinner.",
    "No capes!",
    "You make me want to be a better man.",
    "I'm the dude, so that's what you call me.",
    "It’s not who I am underneath, but what I do that defines me.",
    "I ate his liver with some fava beans and a nice Chianti.",
    "I volunteer as tribute!",
    "We're gonna need a bigger boat.",
    "Leave the gun. Take the cannoli.",
    "Mother of mercy, is this the end of Rico?",
    "Forget it, Jake, it's Chinatown.",
    "I have always depended on the kindness of strangers.",
    "Soylent Green is people!",
    "Snap out of it!",
    "I'm the king of the world!",
    "I'm having an old friend for dinner.",
    "That rug really tied the room together.",
    "A boy's best friend is his mother.",
    "You can't handle the truth!",
    "You're tearing me apart, Lisa!",
    "You complete me.",
    "You talking to me?",
    "It’s alive!",
    "This is my boomstick!",
    "I wish I knew how to quit you.",
    "With great power comes great responsibility.",
    "I'm too old for this shit.",
    "I'm not bad. I'm just drawn that way.",
    "ET phone home.",
    "They're here!",
    "Here's looking at you, kid.",
    "Wax on, wax off.",
    "It's just a flesh wound.",
    "I'm your Huckleberry.",
    "Well, nobody's perfect.",
    "I feel like I'm taking crazy pills!",
    "I'm not even supposed to be here today.",
    "You had me at hello.",
    "I'm just a girl, standing in front of a boy, asking him to love her.",
    "Keep the change, ya filthy animal.",
    "I'm too pretty for God to let me die.",
    "So you're telling me there's a chance.",
    "60% of the time, it works every time.",
    "You're a wizard, Harry.",
    "I am Groot.",
    "I know.",
    "As if!",
    "You're a mean one, Mr. Grinch.",
    "Mischief managed.",
    "I got a jar of dirt!"
];
